---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: task-manager-staging
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  releaseName: task-manager-staging
  targetNamespace: staging
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/task-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: task-manager-staging-values
      optional: false
  dependsOn:
    - name: cloudnative-pg
      namespace: flux-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-staging-values
  namespace: flux-system
data:
  values.yaml: |
    app:
      replicaCount: 1
      image:
        tag: "latest"
        pullPolicy: Always
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      ingress:
        enabled: true
        hosts:
          - host: app.staging.local
            paths:
              - path: /
                pathType: Prefix
      autoscaling:
        enabled: false
    
    postgresql:
      enabled: true
      instances: 1
      persistence:
        size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    dragonfly:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    
    namespace:
      name: staging