---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/main/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: "v1.1.7"
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Default values
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
